import { Session, TimeSlot } from '../types';

export const TIME_SLOTS: TimeSlot[] = [
  // --- JUNE 2 ---
  {
    id: 'j2-slot-1',
    label: 'June 2: 8:00 AM - 9:00 AM',
    startTime: '8:00 AM',
    endTime: '9:00 AM',
  },
  {
    id: 'j2-slot-2',
    label: 'June 2: 9:00 AM - 10:00 AM',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
  },
  {
    id: 'j2-slot-3',
    label: 'June 2: 10:00 AM - 11:00 AM',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
  },
  {
    id: 'j2-slot-4',
    label: 'June 2: 12:00 PM - 1:00 PM',
    startTime: '12:00 PM',
    endTime: '1:00 PM',
  },
  {
    id: 'j2-slot-5',
    label: 'June 2: 1:00 PM - 2:00 PM',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
  },
  {
    id: 'j2-slot-6',
    label: 'June 2: 2:00 PM - 3:00 PM',
    startTime: '2:00 PM',
    endTime: '3:00 PM',
  },
  
  // --- JUNE 3 ---
  {
    id: 'j3-slot-1',
    label: 'June 3: 8:00 AM - 9:00 AM',
    startTime: '8:00 AM',
    endTime: '9:00 AM',
  },
  {
    id: 'j3-slot-2',
    label: 'June 3: 9:00 AM - 10:00 AM',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
  },
  {
    id: 'j3-slot-3',
    label: 'June 3: 10:00 AM - 11:00 AM',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
  },
  {
    id: 'j3-slot-4',
    label: 'June 3: 12:00 PM - 3:00 PM',
    startTime: '12:00 PM',
    endTime: '3:00 PM',
  },
];

const DEFAULT_CAPACITY = 25;

export const INITIAL_SESSIONS: Session[] = [
  // ================= JUNE 2: 8:00 AM START (Slot 1) =================
  {
    id: 'j2-s1-1',
    slotId: 'j2-slot-1',
    title: 'Working Smarter Together: Systems, Communication & Clarity (3 HOURS)',
    description: '8:00-11:00 a.m. This three-hour collaborative workshop is designed for support staff in clerical and operational roles. NOTE: This session spans 8am-11am.',
    presenter: 'Brigid Tileston',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s1-2',
    slotId: 'j2-slot-1',
    title: 'Together Two Twenty & U!',
    description: 'This one-hour interactive workshop equips school district employees with practical, immediately applicable strategies to positively influence district and school culture.',
    presenter: 'Craig Winkelman',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s1-3',
    slotId: 'j2-slot-1',
    title: 'Working Athletic Events',
    description: 'Learn what it takes to work an athletic event. We will go over the basics of running the scoreboard and keeping the scorebook for soccer, football, volleyball, and basketball.',
    presenter: 'Ryan Rubenstein',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s1-4',
    slotId: 'j2-slot-1',
    title: 'Establishing a Healthy Culture',
    description: 'This session explores how individual behaviors and team practices contribute to a positive, respectful, and supportive work environment.',
    presenter: 'Nichole Satera, Pat Waldau, Robert Wright, Nathan Sladky',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s1-5',
    slotId: 'j2-slot-1',
    title: 'Cybersecurity Awareness: Protecting Yourself and Your School',
    description: 'Stay ahead of cyber threats and safeguard your data. Learn how to identify suspicious activity, protect sensitive information, and contribute to a secure school environment.',
    presenter: 'Russell Vander Mey, Hector Ontiveros, Scott Moore',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s1-6',
    slotId: 'j2-slot-1',
    title: 'Supporting Students in Learning Mathematics',
    description: 'We will learn about different approaches, questions, and skills that can be used to support students\' mathematics learning in whole-class, small group, or one-on-one situations.',
    presenter: 'Chris Rohde',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s1-7',
    slotId: 'j2-slot-1',
    title: 'Math Confidence Lab — Making Math Make Sense for Everyone',
    description: 'Join this hands-on session to explore simple, effective ways to support students’ mathematical thinking using visuals and manipulatives.',
    presenter: 'Kelly Hansen',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s1-8',
    slotId: 'j2-slot-1',
    title: 'Incorporating AI Into Your Workflow',
    description: 'Discover how AI-powered tools can streamline your work and take your efficiency to the next level. This workshop will explore practical applications of AI.',
    presenter: 'Ty Gorman',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 2: 9:00 AM START (Slot 2) =================
  {
    id: 'j2-s2-1',
    slotId: 'j2-slot-2',
    title: 'Customer Service',
    description: 'This course focuses on delivering responsive, respectful, and solution-oriented service to students, staff, families, and the community.',
    presenter: 'Nichole Satera, Pat Waldau, Robert Wright, Nathan Sladky',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s2-2',
    slotId: 'j2-slot-2',
    title: 'Special Education 101',
    description: 'Foundations of Special Education, including Laws and Regulations that guide practice and strategies for working with students in the classroom.',
    presenter: 'Jessica Buchanan and Chad May',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s2-3',
    slotId: 'j2-slot-2',
    title: 'Sidekick to Superhero: Elevate your Behavior Management',
    description: 'Gain practical strategies and proven techniques to foster positive behavior, even in the most challenging situations.',
    presenter: 'Sara Jirasek and Lisa West',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s2-4',
    slotId: 'j2-slot-2',
    title: 'Getting Started with Schoology',
    description: 'Learn how to fully support students using Schoology. This course covers login, basic navigation, and the advisor dashboard.',
    presenter: 'Shawndra Shelton',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s2-5',
    slotId: 'j2-slot-2',
    title: 'Guiding Big Feelings in Unstructured Spaces',
    description: 'Explore how the CharacterStrong framework and the Tree of Choices (Roots, Heart, Branches) support students through conflict and problem-solving.',
    presenter: 'Denise Anderson & Antonio Diaz',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s2-6',
    slotId: 'j2-slot-2',
    title: 'Your Impact Matters — How Classroom Assistants Grow Learner Agency',
    description: 'This session helps Classroom Assistants recognize and strengthen moments of agency by using empowering language and encouraging reflection.',
    presenter: 'Kelly Hansen',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s2-7',
    slotId: 'j2-slot-2',
    title: 'The Power of Self-Efficacy',
    description: 'The power of aligning student interests with instructional practices.',
    presenter: 'Dr. Stephen McWilliams',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s2-8',
    slotId: 'j2-slot-2',
    title: 'Setting Limits and Positive Reinforcement',
    description: 'Learn practical strategies to increase appropriate behavior, identify meaningful reinforcers, and set consistent, respectful limits.',
    presenter: 'Melissa Pohl and Lauren Lambourn',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 2: 10:00 AM START (Slot 3) =================
  {
    id: 'j2-s3-1',
    slotId: 'j2-slot-3',
    title: 'Introduction to Ad Hoc Reporting Student Data',
    description: 'Covers Filter Designer (Student Data), Filter & Data Types, Selection Editor, Query Wizard, Community Resources, Saving & Sharing.',
    presenter: 'Tracy Harper',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s3-2',
    slotId: 'j2-slot-3',
    title: 'School Health Preparedness',
    description: 'Topics: Respiratory hygiene, Bodily fluid exposure, EpiPen, Seizure care, Opioid overdose, Cardiac Emergencies, AEDs, Choking, Injuries, etc.',
    presenter: 'Bridget Heroff',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s3-3',
    slotId: 'j2-slot-3',
    title: 'Google Drive Tips and Tricks: A Beginner’s Workshop',
    description: 'Unlock the potential of your digital office. Learn how to upload, organize, and search for documents to keep your daily operations running smoothly.',
    presenter: 'Amy Koegel & Becky Brichta & Rita Miller',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s3-4',
    slotId: 'j2-slot-3',
    title: 'Timing and Scoring for Athletics',
    description: 'Provide participants with the knowledge and confidence to help as a scorer or timer for various athletic events throughout the school year.',
    presenter: 'Tim Haupt & Brad Gillette',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s3-5',
    slotId: 'j2-slot-3',
    title: 'The Stimulus Question for All Learners 6-12',
    description: 'Discuss how to help students answer critical thinking questions that require combining provided source material with prior knowledge.',
    presenter: 'John Roncone, Julie Baylor, Mitch Beck',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s3-6',
    slotId: 'j2-slot-3',
    title: 'AI IRL (In Real Life)',
    description: 'A practical, hands-on session designed to help you use AI in ways that make your days easier at work and at home.',
    presenter: 'Joe Robinson',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s3-7',
    slotId: 'j2-slot-3',
    title: 'Canva for Beginners',
    description: 'This course will cover login, basic navigation, projects and tools in Canva.',
    presenter: 'Shawnda Shelton',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s3-8',
    slotId: 'j2-slot-3',
    title: 'Budget Brass Tacks',
    description: 'Dive into the how and why associated with building budgets, bank deposits, P.O.\'s, P-cards, and Data Mining Reports.',
    presenter: 'Josie Morrisroe, Mary Harrington & Erica Ward',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 2: 12:00 PM START (Slot 4) =================
  {
    id: 'j2-s4-1',
    slotId: 'j2-slot-4',
    title: 'Supporting Student Learning Through Purposeful Practice (3 HOURS)',
    description: '12:00-3:00 p.m. Strengthen classified staff understanding of their critical role in supporting student learning and independence. NOTE: This session spans 12pm-3pm.',
    presenter: 'Sarah Rabe',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s4-2',
    slotId: 'j2-slot-4',
    title: 'Make AI your Ride or Die (3 HOURS)',
    description: '12:00-3:00 p.m. Learn how to offload repetitive tasks, organize information instantly, and visualize your ideas using Gemini, NotebookLM, and Snorkl. NOTE: This session spans 12pm-3pm.',
    presenter: 'Shawndra Shelton/Kathrine Clarke',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s4-3',
    slotId: 'j2-slot-4',
    title: 'Communicating Visually through Sketchnoting',
    description: 'Learn about and practice the sketchnoting process using your district-assigned iPad and Logitech Crayon.',
    presenter: 'Matt Fuller',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s4-4',
    slotId: 'j2-slot-4',
    title: 'A Pathway of Support: Special Education Services',
    description: 'Explore the district’s continuum of special education services and specialized programs, from least to most intensive supports.',
    presenter: 'Kat Romero and Jordan Anderson',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s4-5',
    slotId: 'j2-slot-4',
    title: 'Standard Reunification Method Training',
    description: 'Overview of the Standard Reunification Method (SRM), a nationally recognized approach to safely reunifying students with parents following an emergency.',
    presenter: 'Teresa Reiche, Bobby Benjamin, Jason Bryant, Brad Gillette',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s4-6',
    slotId: 'j2-slot-4',
    title: 'Multilingual Learners in Barrington 220',
    description: 'Explore strategies we can all use to better support and connect with our multilingual learners.',
    presenter: 'Becky Wiegel',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s4-7',
    slotId: 'j2-slot-4',
    title: 'Canva - So Great!!',
    description: 'Crash course in the basics of CANVA.',
    presenter: 'Babbi Barreiro & Julie Baylor',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s4-8',
    slotId: 'j2-slot-4',
    title: 'Collaborative Roundtable: BSEO Instructional Evaluation Rubric',
    description: 'Explore the BSEO Instructional Evaluation Rubric in depth, examining key domains and evaluation ratings through real-world examples.',
    presenter: 'Megan Russell and Kathy Zachwieja',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 2: 1:00 PM START (Slot 5) =================
  {
    id: 'j2-s5-1',
    slotId: 'j2-slot-5',
    title: 'Service Log Completion for 1:1 Assistants',
    description: 'Participants will learn how to complete their weekly service logs for Medicaid billing.',
    presenter: 'Jackie Nehs and Debbie Koenen',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s5-2',
    slotId: 'j2-slot-5',
    title: 'Helping our Multilingual Students Succeed',
    description: 'Learn more about your role as a bilingual aide and share ideas with others who play this vital role in our schools!',
    presenter: 'Kathryn Wolfkiel',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s5-3',
    slotId: 'j2-slot-5',
    title: 'Board Credit / Reimbursement Review',
    description: 'Help better understand the board credit and reimbursement process along with some tips and tricks.',
    presenter: 'Mona Reyes & Amanda Michael',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s5-4',
    slotId: 'j2-slot-5',
    title: 'Activating Empathy',
    description: 'Activating empathy with students and colleagues to positively impact relationships.',
    presenter: 'Micah Korb',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s5-5',
    slotId: 'j2-slot-5',
    title: 'Brain Games for Life',
    description: 'Supports adult wellness by exploring how simple, enjoyable brain games and cognitive challenges can strengthen mental agility, focus, and overall brain health.',
    presenter: 'Becky Gill & Heather Schumacher',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s5-6',
    slotId: 'j2-slot-5',
    title: 'The Power of Neuro-affirming Language',
    description: 'Examine common phrases used in school settings and learn how small shifts in language can reduce power struggles and promote dignity.',
    presenter: 'Chelsea Hedges',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s5-7',
    slotId: 'j2-slot-5',
    title: 'Understanding Your Budget',
    description: 'Cover how to select proper accounts for your POs, review your budget in Skyward, and how current year spending can provide a base for next year.',
    presenter: 'Jen Prindle, Lauren Borowski',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 2: 2:00 PM START (Slot 6) =================
  {
    id: 'j2-s6-1',
    slotId: 'j2-slot-6',
    title: 'Understanding Your Classroom AV (Audio/Visual)',
    description: 'Mastering Classroom AV: ViewSonic & Apple TV. Eliminate tech friction and maximize lesson impact.',
    presenter: 'Mark Polzin',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s6-2',
    slotId: 'j2-slot-6',
    title: 'Benefitsolver & Skyward Employee Access',
    description: 'Dive into Benefitsolver as well as Skyward Employee Access to help build a deeper understanding of how these systems work.',
    presenter: 'Kris Benoit & Kelly Gruenfeld',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s6-3',
    slotId: 'j2-slot-6',
    title: 'Website Navigation',
    description: 'Touring features of the website that are beneficial to employees.',
    presenter: 'Charles Parkinson',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s6-4',
    slotId: 'j2-slot-6',
    title: 'True Time 101',
    description: 'Join us for beginners guide for True Time. We will cover how to enter your time, modify time, view/submit time.',
    presenter: 'Cindy Morales & Peg Cleary',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s6-5',
    slotId: 'j2-slot-6',
    title: 'Next-Level iPad: iOS 26 Updates in Action',
    description: 'Fast, focused walkthrough of the latest iOS 26 updates for iPad. Explore the most impactful new features.',
    presenter: 'Rebecca Brichta',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j2-s6-6',
    slotId: 'j2-slot-6',
    title: 'When the Chips Are Down: Understanding Behavior',
    description: 'Explore how frustration builds when demands exceed a student’s current abilities. Focus on recognizing stress signals and responding effectively.',
    presenter: 'Chelsea Hedges',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 3: 8:00 AM START (Slot 1) =================
  {
    id: 'j3-s1-1',
    slotId: 'j3-slot-1',
    title: 'Little Readers, Big Tools (3 HOURS)',
    description: '8:00-11:00 a.m. Interactive session for those supporting students in small-group literacy instruction. Explore key resources like Rigby Readers. NOTE: This session spans 8am-11am.',
    presenter: 'Joslyn Katz',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s1-2',
    slotId: 'j3-slot-1',
    title: 'Getting Started with Seesaw',
    description: 'This course will cover login, basic navigation, and best practices for supporting students.',
    presenter: 'Shawndra Shelton',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s1-3',
    slotId: 'j3-slot-1',
    title: 'Navigating the Staff Section of the Website',
    description: 'Learn how to locate and use key resources, accessing Policies, Administrative Procedures, and current District Initiatives.',
    presenter: 'Josh Carpenter & Cassy Mrowicki',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s1-4',
    slotId: 'j3-slot-1',
    title: 'Hands-on Exploration of LAMP and UNITY AAC Apps',
    description: 'Give participants hands-on time to explore both apps, with a special focus on the new UNITY AAC app alongside LAMP Words for Life.',
    presenter: 'Kelly Key',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s1-5',
    slotId: 'j3-slot-1',
    title: 'Regional Office of Education Annual Inspections',
    description: 'Review common compliance areas, documentation expectations, and staff responsibilities in supporting Health and Life Safety inspections.',
    presenter: 'Nichole Satera, Pat Waldau, Robert Wright, Nathan Sladky',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s1-6',
    slotId: 'j3-slot-1',
    title: 'School Health Preparedness',
    description: 'Topics: Respiratory hygiene, Bodily fluid exposure, EpiPen, Seizure care, Opioid overdose, Cardiac Emergencies, AEDs, etc.',
    presenter: 'Bridget Heroff',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s1-7',
    slotId: 'j3-slot-1',
    title: 'Culturally Responsive Teaching and Leading',
    description: 'Increase your knowledge, skill, will, and capacity to meet our diverse learners in the most effective ways possible.',
    presenter: 'Tony Bradburn',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 3: 9:00 AM START (Slot 2) =================
  {
    id: 'j3-s2-1',
    slotId: 'j3-slot-2',
    title: 'Making Worksheets Accessible with AT Tools',
    description: 'Learn how to take a picture worksheet and make it accessible on the iPad using Live Text, Notability, and Orbit Note.',
    presenter: 'Kelly Key',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s2-2',
    slotId: 'j3-slot-2',
    title: 'Service Excellence in the Main Office',
    description: 'Explore tailored strategies for communicating with parents, staff, and students. Move beyond corporate scripts to focus on empathy-driven service.',
    presenter: 'Jaclyn Sheldon, Jeff Helberg, Travis Lobbins',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s2-3',
    slotId: 'j3-slot-2',
    title: 'Google Drive Tips and Tricks: A Beginner’s Workshop',
    description: 'Unlock the potential of your digital office. Learn how to upload, organize, and search for documents.',
    presenter: 'Amy Koegel & Becky Brichta & Rita Miller',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s2-4',
    slotId: 'j3-slot-2',
    title: 'Introduction to Ad Hoc Reporting Student Data',
    description: 'Covers Filter Designer (Student Data), Filter & Data Types, Selection Editor, Query Wizard, Community Resources.',
    presenter: 'Tracy Harper',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s2-5',
    slotId: 'j3-slot-2',
    title: 'Incident IQ – Work Ticket Submission',
    description: 'Overview of Incident IQ, the district’s new work ticket submission system. Learn how to submit, track, and manage service requests.',
    presenter: 'Nichole Satera, Pat Waldau, Robert Wright, Nathan Sladky',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s2-6',
    slotId: 'j3-slot-2',
    title: 'Google Sheets',
    description: 'Introduction, refresher, or new techniques to improve your productivity with Google Sheets or Excel.',
    presenter: 'Sarah Lager',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 3: 10:00 AM START (Slot 3) =================
  {
    id: 'j3-s3-1',
    slotId: 'j3-slot-3',
    title: 'Empowering Teaching Assistants',
    description: 'Focus on improving teaching methods to boost student success through evidence-based strategies and small-group activities.',
    presenter: 'Kelly Haradon and Zach Ernst',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s3-2',
    slotId: 'j3-slot-3',
    title: 'Keep Students on Task and Engaged',
    description: 'Cover using screen time to block/monitor device usage, guided access, Apple Classroom, and Nearpod.',
    presenter: 'Marci Knecht, Patti Hecker, Suzy Chiappetta',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s3-3',
    slotId: 'j3-slot-3',
    title: 'Read and Write AT Add-on Keyboard Training',
    description: 'Hands-on experience with the Read&Write add-on keyboard. Features include phonetic word prediction, grammar check, voice typing, and more.',
    presenter: 'Kelly Key',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s3-4',
    slotId: 'j3-slot-3',
    title: 'TBD',
    description: 'TBD',
    presenter: 'Jeanine Stark',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s3-5',
    slotId: 'j3-slot-3',
    title: 'Canva for Beginners',
    description: 'This course will cover login, basic navigation, projects and Canva tools.',
    presenter: 'Shawndra Shelton',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s3-6',
    slotId: 'j3-slot-3',
    title: 'Setting Limits and Positive Reinforcement',
    description: 'Learn practical strategies to increase appropriate behavior, identify meaningful reinforcers, and set consistent, respectful limits.',
    presenter: 'Melissa Pohl and Lauren Lambourn',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },
  {
    id: 'j3-s3-7',
    slotId: 'j3-slot-3',
    title: 'Embedding Executive Functioning Strategies',
    description: 'Exposed to evidence-based practices to support executive functions with practical strategies that can be implemented quickly.',
    presenter: 'Sophie Niemaszyk',
    room: 'BMS Station Campus Room TBD',
    capacity: DEFAULT_CAPACITY,
    enrolled: 0,
  },

  // ================= JUNE 3: 12:00 PM START (Slot 4) =================
  {
    id: 'j3-s4-1',
    slotId: 'j3-slot-4',
    title: 'Character Strong Brain and Behavior Training (3 HOURS)',
    description: '12:00-3:00 p.m. Half-day training designed to support classified staff with practical strategies for working with students. NOTE: This session spans 12pm-3pm.',
    presenter: 'Character Strong',
    room: 'BMS Station Campus Room TBD',
    capacity: 400, // SPECIAL CAPACITY
    enrolled: 0,
  },
];
